parameters:
    database_driver:   pdo_pgsql
    database_host:     127.0.0.1
    database_port:     5432
    database_name:     problem-make
    database_user:     bogdanvera
    database_password: ~

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
